### ISSUE TITLE
example not working ....

### ISSUE THREAD

**Issue by amaydiam** [vinaysshenoy/mugen#11] opened 2015-07-30 23:48 UTC
I try to run example, but it;s not to load more ....

**Comment by mipreamble** [comment] 2015-07-31 00:05
@amaydiam I just ran the sample on an emulator with Android version 4.4.2
Sample is running fine. Please check with your device.

Note: Needs network to run the sample.

**Comment by amaydiam** [comment] 2015-07-31 00:50
yes, network  is ON
The first load , the data is received . But Load more function it's not work.
I ran on nexus 5 (Lolipop) and samsung Tab 3 (Kitkat).
like this :
https://vid.me/DkUy

**Comment by vinaysshenoy** [comment] 2015-07-31 09:41
@amaydiam We have identified the issue. The library requires enough items loaded on the first go to become scrollable, but it seems on high density screens, the number of items loaded is not. The issue is not with the library, but with the sample app. We will change the sample to load more items on high density screens.

I will also look into the library to allow configuring an automatic load if the first batch is not scrollable.

**Comment by mipreamble** [comment] 2015-07-31 11:25
@amaydiam Thank you notifying the issue. We have updated the sample to load items based on the screen height. 

@vinaysshenoy Please review the PR
https://github.com/mipreamble/mugen/commit/ef371d284a8d1ac3196078a3c40d6d47f0d882cc

The sample will be available soon for you to test.

**Comment by vinaysshenoy** [comment] 2015-07-31 16:16
Fixed in 2d18149b71c907320057a68bee4cd0a8dfa54d14.

**Closed by vinaysshenoy** 2015-07-31 16:16 UTC
